### PR TITLE
Hit the API

### PR DESCRIPTION
**Pull request by Somdotta07**
- Fetched API
- Used `async` and `await` JavaScript features to consume the API.
- Created a new game with the name by using the API.
- Implemented the "Refresh" button to receive data from the API 
- Implemented the form "Submit" button to send data to the API

### CODE REVIEW

**Comment by Somdotta07** [comment]
_I'll edit the READMe.md file by the end of last day's project.Please consider._

**Review by henatan99 — CHANGES_REQUESTED** [review]
Hi @Somdotta07 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>


## Required Changes ♻️
- [x] You did an amazing work :clap: :clap: :clap: . One thing to work on before moving to your next milestone is updating your readme. Please update links and instructions, so that potential collaborators and employers find you and also be able to clone and use your code. :pray: 
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Somdotta07** [comment]
Thanks for the review, except the README.md, do I need to change anything else?

**Comment by Somdotta07** [comment]
- Updated README.md file as suggested by the previous reviewer.

**Comment by henatan99** [comment]
> _I'll edit the READMe.md file by the end of last day's project.Please consider._

Dear @Somdotta07, I understand that you can make the final version of your readme at the last milestone. But, I have asked of the basic information that needs to be included so that even reviewers find it relevant like setup, installation, and usage. Thank you for making the changes though.

**Review by henatan99 — APPROVED** [review]
Hi @Somdotta07 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
